name: Build and Push
on:
  push:
    branches:
      - v[0-100].[0-100]
      - test
  

jobs:
    slarkNotification:    
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:  
            - uses: actions/checkout@v2
            - name: Run Trivy vulnerability scanner in repo mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'test.txt'
                severity: ${{vars.TRIVY_SEVERITY}}
                exit-code: '1'

#            - name: Create File
#              run: echo "hello" > output.txt

#            - name: Debug OUTPUT
#              run: |
#                pwd
#                ls -la
            - name: Slack Notification
              if: ${{ success() }}
              uses: rtCamp/action-slack-notify@v2
              
              env:
                SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                SLACK_MSG_AUTHOR: SyBruh
                SLACK_TITLE: Image build and signed
                SLACK_MESSAGE: "*Name:* Testing\n*Metriculation:* abc123\n*Email:* <example.com|abc123>\n*Git:* <example.com|abc123>\n*Image:* <example.com|abc123>"
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
              name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: user/app:latest

            - name: Slack Notification
              if: ${{ failure() }}
              uses: rtCamp/action-slack-notify@v2
                
              env:
                SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                SLACK_MSG_AUTHOR: SyBruh
                SLACK_TITLE: Scan Failed Aiyo
                SLACK_MESSAGE: "Fail Trivy Scan, Check that txt out"

            - name: file upload  
              if: ${{ failure() }}
              uses: MeilCli/slack-upload-file@v3
              with:
                slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
                channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
                file_path: '/home/runner/work/CICD_workshop/CICD_workshop/test.txt'
                initial_comment: 'Upload by Aiyo'