name: Build and Push
on:
  push:
    branches:
      - v[0-9]+.[0-9]+
  

jobs:
    slarkNotification:    
        name: Slack Notification
        if: (!contains(github.event.head_commit.message, '#NORUN'))
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          id-token: write
        steps:  
            - uses: actions/checkout@v2
            - name: Install Cosign
              uses: sigstore/cosign-installer@v3.1.1
              with: 
                cosign-release: 'v2.2.0'
            - name: Run Trivy vulnerability scanner in repo mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'test.txt'
                severity: ${{vars.TRIVY_SEVERITY}}
                exit-code: '1'

#            - name: Create File
#              run: echo "hello" > output.txt

#            - name: Debug OUTPUT
#              run: |
#                pwd
#                ls -la
            - name: Slack Notification
              if: ${{ success() }}
              uses: rtCamp/action-slack-notify@v2
              
              env:
                SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                SLACK_MSG_AUTHOR: SyBruh
                SLACK_TITLE: Image build and signed
                SLACK_MESSAGE: "*Name:* Swam Yay Pyae Hmuu\n*Metriculation:* A0285948E\n*Email:* e1221760@u.nus.edu\n*Git:* <https://github.com/SyBruh/CICD_workshop|https://github.com/SyBruh/CICD_workshop>\n*Image:* <https://hub.docker.com/repository/docker/swamyay/cicdworkshop/|https://hub.docker.com/repository/docker/swamyay/cicdworkshop/>"
            
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
              name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - id: docker_meta
              uses: docker/metadata-action@v4.4.0
              with:
                images: swamyay/cicdworkshop
                tags: ${{github.sha}}
            -
              name: Build and push
              uses: docker/build-push-action@v5
              id: build-and-push
              with:
                push: true
                tags: ${{ steps.docker_meta.outputs.tags }}
            
            - name: Sign image with a key
              run: |
                cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
              env:
                TAGS: ${{ steps.docker_meta.outputs.tags }}
                COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
                COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
                DIGEST: ${{ steps.build-and-push.outputs.digest }}
                

            - name: Slack Notification
              if: ${{ failure() }}
              uses: rtCamp/action-slack-notify@v2
                
              env:
                SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK_URL}}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
                SLACK_MSG_AUTHOR: SyBruh
                SLACK_TITLE: Scan Failed - Swam Yay Pyae Hmuu
                SLACK_MESSAGE: "Fail Trivy Scan, Check the report for detiails"
                SLACK_COLOR: ${{job.status}}

            - name: file upload  
              if: ${{ failure() }}
              uses: MeilCli/slack-upload-file@v3
              with:
                slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
                channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
                file_path: '/home/runner/work/CICD_workshop/CICD_workshop/test.txt'
                initial_comment: 'Upload by Swam Yay Pyae Hmuu'
