name: Build and Push
on:
  push:
    branches:
      - v[0-100].[0-100]
      - test
  

jobs:
    slarkNotification:    
        name: Slack Notification
        runs-on: ubuntu-latest
        steps:  
            - uses: actions/checkout@v2
            - name: Run Trivy vulnerability scanner in repo mode
              uses: aquasecurity/trivy-action@master
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'table'
                output: 'test.txt'
                severity: 'HIGH,CRITICAL .'